type Query {
  productCategories: [ProductCategory]
  productCategory(id: Int!): ProductCategory
}
type Mutation {
  createProductCategory(input:ProductCategoryInput): Boolean
  updateProductCategory(id:Int!,input:ProductCategoryInput):Boolean
  removeProductCategory(id:Int!):Boolean
}
input ProductCategoryInput{
  category_name:String
}
type ProductCategory {
  id: Int
  category_name: String
  products: [Product]
}
