type Query {
  users: [User]
  user(id: Int!): [User]
}
type User {
  id: Int
  email: String
  username: String
  fullaname: String
}
type Mutation {
  userLogin(username: String!, password: String!): String!
  createUser(input: UserInput): Boolean
}
input UserInput {
  id: Int
  email: String
  username: String
  password:String
  fullaname: String
}
